### ISSUE TITLE
Export and Save Results fails

### ISSUE THREAD

**Issue by krvladislav** [ultram4rine/sqltools-clickhouse-driver#27]
Hi.

I have ultram4rine.sqltools-clickhouse-driver v0.1.0 installed.

When I click 'Export' button in a results tab I get no effect. 

When I try to click 'Save Results' button I receive this message: _Running the contributed command: 'sqltools.saveResults' failed._

Is this a bug? Or do you have plans to support the export?

**Comment by ultram4rine** [comment]
Seems like a bug, because this functionality implemented in SQLTools, not in drivers. I also found that other features of query results view not working, like pages, instead of 50 on each page, view contains all.
Anyway, thanks for reporting, I will try to figure it out.
