### ISSUE TITLE
Query metrics

### ISSUE THREAD

**Issue by roborourke** [ultram4rine/sqltools-clickhouse-driver#281]
Thanks for this extension! It's really handy running queries directly.

Not knowing anything about the SQLTools parent extension I wanted to ask / suggest a feature based on the `/play` endpoint clickhouse provides.

It shows some metrics for the query:

- elapsed time
- read rows
- bytes of data scanned

They're super useful for debugging the efficiency of queries, for instance if data scanned is larger than the db itself then the query is scanning the table multiple times.

**Comment by ultram4rine** [comment]
Hi @roborourke, after merging #286 query metrics will appear in `SQL Console: Messages` window like that:
![image](https://user-images.githubusercontent.com/42237599/215550074-5fb0dad9-4fd5-4635-9cf0-2d84649479c9.png)

**Comment by roborourke** [comment]
@ultram4rine Ace! Thanks for this
