### ISSUE TITLE
New icons

### ISSUE THREAD

**Issue by ultram4rine** [ultram4rine/sqltools-clickhouse-driver#374]
Looks like ClickHouse has a redesign: https://clickhouse.com/

Need to update icons to something like:
![image](https://user-images.githubusercontent.com/42237599/230792521-9bca10ec-48ae-4a01-a17e-75b1c2e3b19d.png)

**Comment by amartyaroy** [comment]
Hi @ultram4rine 
I can work in this issue.Can you please tell your requirements more if you have

**Comment by ultram4rine** [comment]
Hi @amartyaroy, sure.
Here are requirements from sqltools docs: https://vscode-sqltools.mteixeira.dev/en/contributing/support-new-drivers#4-create-icons
Extension icon should be like `default`, but 128x128.
Also I guess `#FCFF74` color would hard to see with white theme, so there are should be white variant with `#000000` I guess (see how it looks in white theme of [clickhouse docs](https://clickhouse.com/docs/en/intro) at top left corner), but icons for white/dark themes aren't supported by sqltools for now (mtxr/vscode-sqltools#992), so I think I need to take a look at it.
And update `package.json` `galleryBanner.color` to something dark, I guess `#000000` too:
https://github.com/ultram4rine/sqltools-clickhouse-driver/blob/241e527726778b5c259021f6fa83257b9a489b85/package.json#L47
