### ISSUE TITLE
ssl support

### ISSUE THREAD

**Issue by juztnelubka** [ultram4rine/sqltools-clickhouse-driver#386]
Hi, i can't find how to connect to database if it requires ssl certificate

**Comment by ultram4rine** [comment]
Looks like it's needed to update connection schema.
NodeJS client [has](https://clickhouse.com/docs/en/integrations/language-clients/nodejs#configuration) TLS configuration.

https://clickhouse.com/docs/en/integrations/language-clients/nodejs#tls-certificates

**Comment by arkazantsev8** [comment]
Hi, i would really appreciate this feature!

**Comment by lukyanenkomax** [comment]
Is there any workaround while you are working on this pull request?

**Comment by ultram4rine** [comment]
> Is there any workaround while you are working on this pull request?

You can download and install `vsix` artifact from job: https://github.com/ultram4rine/sqltools-clickhouse-driver/actions/runs/5018156158
